versions:
- name: 1.6.17
  code: 1617
  latest: true
- name: 1.8.5
  code: 1805
  latest: true
- name: 1.8.4
  code: 1804
- name: 1.6.16
  code: 1616
- name: 1.8.3
  code: 1803
- name: 1.8.2
  code: 1802
- name: 1.8.1
  code: 1801
- name: 1.8.0
  code: 1800
- name: 1.6.15
  code: 1615
- name: 1.6.14
  code: 1614
- name: 1.6.13
  code: 1613
- name: 1.6.12
  code: 1612
- name: 1.6.11
  code: 1611